services:
  media-server:
    container_name: media-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 1935:1935
    networks:
      - media-server

networks:
  media-server:
    driver: bridge
    name: media-server
